import { describe, expect, it } from "vitest";
import { Coordinator } from "./coordinator";
import type { SubAgentEnvelope } from "../types";

describe("Coordinator Planning & Synthesis", () => {
	it("parses valid JSON upfront plan generated by LLM", () => {
		const mockLlmOutput = JSON.stringify({
			planId: "plan-test-1",
			userGoal: "Check status of git repository",
			tasks: [
				{
					taskId: "task-1",
					title: "Check git status and log",
					reasoning: "low",
					contextRequirement: "git repo status",
					expectedOutputSize: "small",
					priority: "high",
					requiredCapabilities: ["git.log"],
					dependencies: [],
					assignedTools: ["git.log"],
					estimatedTokens: 600,
				},
			],
			estimatedTotalTokens: 1000,
			estimatedExecutionTimeSeconds: 4,
			verify: false,
		});

		const coordinator = new Coordinator();
		const plan = coordinator.parsePlanOutput(mockLlmOutput);

		expect(plan.planId).toBe("plan-test-1");
		expect(plan.tasks).toHaveLength(1);
		expect(plan.tasks[0].requiredCapabilities).toContain("git.log");
	});

	it("throws an error if plan JSON violates required schema", () => {
		const invalidOutput = JSON.stringify({
			planId: "invalid",
			// missing tasks and userGoal
		});

		const coordinator = new Coordinator();
		expect(() => coordinator.parsePlanOutput(invalidOutput)).toThrow();
	});

	it("synthesizes final answer from multiple sub-agent envelopes", () => {
		const coordinator = new Coordinator();
		const envelopes: SubAgentEnvelope[] = [
			{
				status: "success",
				summary: "Git repository is clean on branch main",
				evidence: "git status reports nothing to commit",
				confidence: "high",
				warnings: [],
				resultPayload: { branch: "main", clean: true },
			},
		];

		const synthesis = coordinator.synthesizeFinalAnswer({
			userGoal: "Check status",
			envelopes,
		});

		expect(synthesis).toContain("Git repository is clean on branch main");
		expect(synthesis).toContain("Summary");
	});
});
