import { z } from "zod";

/**
 * Reasoning level required for a specific task.
 */
export const ReasoningLevelSchema = z.enum(["low", "medium", "high"]);
export type ReasoningLevel = z.infer<typeof ReasoningLevelSchema>;

/**
 * Output size estimate for budgeting tokens.
 */
export const OutputSizeSchema = z.enum(["small", "medium", "large"]);
export type OutputSize = z.infer<typeof OutputSizeSchema>;

/**
 * Task priority.
 */
export const PrioritySchema = z.enum(["low", "medium", "high", "critical"]);
export type Priority = z.infer<typeof PrioritySchema>;

/**
 * Metadata profile describing the requirements of a single task (Section 11).
 */
export const TaskRequirementProfileSchema = z.object({
	taskId: z.string(),
	title: z.string(),
	reasoning: ReasoningLevelSchema,
	contextRequirement: z.string(),
	expectedOutputSize: OutputSizeSchema,
	priority: PrioritySchema,
	requiredCapabilities: z.array(z.string()),
});
export type TaskRequirementProfile = z.infer<typeof TaskRequirementProfileSchema>;

/**
 * A scheduled task within the upfront plan.
 */
export const PlannedTaskSchema = TaskRequirementProfileSchema.extend({
	dependencies: z.array(z.string()).default([]),
	assignedModel: z.string().optional(),
	assignedTools: z.array(z.string()).default([]),
	estimatedTokens: z.number().int().positive().default(500),
});
export type PlannedTask = z.infer<typeof PlannedTaskSchema>;

/**
 * The complete upfront plan generated by the Coordinator (Sections 6 & 16).
 */
export const PlanSchema = z.object({
	planId: z.string(),
	userGoal: z.string(),
	tasks: z.array(PlannedTaskSchema),
	estimatedTotalTokens: z.number().int().positive(),
	estimatedExecutionTimeSeconds: z.number().int().positive().default(10),
	verify: z.boolean().default(false),
});
export type Plan = z.infer<typeof PlanSchema>;

/**
 * Status of sub-agent task execution.
 */
export const SubAgentStatusSchema = z.enum(["success", "error", "blocked"]);
export type SubAgentStatus = z.infer<typeof SubAgentStatusSchema>;

/**
 * Standardized communication envelope returned by every sub-agent (Section 22).
 */
export const SubAgentEnvelopeSchema = z.object({
	status: SubAgentStatusSchema,
	summary: z.string(),
	evidence: z.string(),
	confidence: z.enum(["high", "medium", "low"]),
	warnings: z.array(z.string()).default([]),
	resultPayload: z.record(z.string(), z.any()).default({}),
});
export type SubAgentEnvelope = z.infer<typeof SubAgentEnvelopeSchema>;

/**
 * Model capability metadata for routing (Section 9).
 */
export interface ModelMetadata {
	modelId: string;
	provider: "groq";
	contextWindow: number;
	maxOutputTokens: number;
	supportsToolCalling: boolean;
	reasoningTier: "low" | "medium" | "high";
	tokensPerMinute: number;
	requestsPerMinute: number;
	dailyTokenCeiling?: number;
	dailyRequestCeiling?: number;
}
